version: '3.1'

services:
  tasks_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "tasks_db"
    ports:
      - "3306:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql 
